// import Slideimg from "../../Images/slideProductimg.png";

export const HomeSliderData = [
  {
    id: "52977",
    title: "One (1) 550g Tin of Milky Way Kuih Kapit",
    subtitle: "milky way food industries (3 damansara)",
    limitedOffer: "limited Lime offer",
    regularPrice: "160",
    offerPrice: "48",
    productImg: "https://i.ibb.co/0ZVpV4v/slide-Productimg.png",
  },
  {
    id: "53060",
    title: "One (1) 550g Tin of Milky Way Kuih Kapit",
    subtitle: "milky way food industries (3 damansara)",
    limitedOffer: "limited Lime offer",
    regularPrice: "160",
    offerPrice: "48",
    productImg: "https://i.ibb.co/0ZVpV4v/slide-Productimg.png",
  },
  {
    id: "52978",
    title: "One (1) 550g Tin of Milky Way Kuih Kapit",
    subtitle: "milky way food industries (3 damansara)",
    limitedOffer: "limited Lime offer",
    regularPrice: "160",
    offerPrice: "48",
    productImg: "https://i.ibb.co/0ZVpV4v/slide-Productimg.png",
  },
  {
    id: "53026",
    title: "One (1) 550g Tin of Milky Way Kuih Kapit",
    subtitle: "milky way food industries (3 damansara)",
    limitedOffer: "limited Lime offer",
    regularPrice: "160",
    offerPrice: "48",
    productImg: "https://i.ibb.co/0ZVpV4v/slide-Productimg.png",
  },
];

export const CategoryData = [
  {
    id: "c1",
    cImg: "https://i.ibb.co/Svfq4bh/cimg1.png",
    cName: "Cake & Milk",
    cQuantity: "126",
    bgColor: "bg-orange-300",
    cId: "cake-milk",
  },
  {
    id: "c2",
    cImg: "https://i.ibb.co/Jphx51S/cimg2.png",
    cName: "Desert",
    cQuantity: "126",
    bgColor: "bg-red-500",
    cId: "desert",
  },
  {
    id: "c3",
    cImg: "https://i.ibb.co/Svfq4bh/cimg1.png",
    cName: "Cake & Milk",
    cQuantity: "126",
    bgColor: "bg-amber-400",
    cId: "coffes-teas",
  },
  {
    id: "c4",
    cImg: "https://i.ibb.co/Jphx51S/cimg2.png",
    cName: "Desert",
    cQuantity: "126",
    bgColor: "bg-yellow-400",
    cId: "vegetable",
  },
  {
    id: "c5",
    cImg: "https://i.ibb.co/Svfq4bh/cimg1.png",
    cName: "Cake & Milk",
    cQuantity: "126",
    bgColor: "bg-lime-400",
    cId: "cake-milk",
  },
  {
    id: "c6",
    cImg: "https://i.ibb.co/Jphx51S/cimg2.png",
    cName: "Desert",
    cQuantity: "126",
    bgColor: "bg-emerald-400",
    cId: "desert",
  },
  {
    id: "c7",
    cImg: "https://i.ibb.co/Svfq4bh/cimg1.png",
    cName: "Cake & Milk",
    cQuantity: "126",
    bgColor: "bg-cyan-400",
    cId: "coffes-teas",
  },
  {
    id: "c8",
    cImg: "https://i.ibb.co/Jphx51S/cimg2.png",
    cName: "Desert",
    cQuantity: "126",
    bgColor: "bg-red-400",
    cId: "vegetable",
  },
];
